apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jax-cpu-job
  namespace: default
spec:
  failurePolicy:
    maxRestarts: 2
  network:
    enableDNSHostnames: true
    subdomain: jax-cpu-job
  replicatedJobs:
    - name: workers
      replicas: 1
      template:
        spec:
          parallelism: 2
          completions: 2
          backoffLimit: 0
          completionMode: Indexed
          template:
            metadata:
              labels:
                jobset.x-k8s.io/jobset-name: jax-cpu-job
            spec:
              subdomain: jax-cpu-job
              affinity:
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                          - key: jobset.x-k8s.io/jobset-name
                            operator: In
                            values: ["jax-cpu-job"]
                      topologyKey: "kubernetes.io/hostname"
              nodeSelector:
                cloud.google.com/gke-nodepool: default-pool
              restartPolicy: Never
              containers:
                - name: jax-cpu-worker
                  image: us-central1-docker.pkg.dev/jax-multinode-1010/jax-gke-repo/jax-cpu-multinode:latest
                  ports:
                    - containerPort: 1234
                      name: coordinator
                  env:
                    - name: JOB_COMPLETION_INDEX
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
                    - name: XLA_FLAGS
                      value: "--xla_force_host_platform_device_count=4"
                    - name: NUM_PROCESSES
                      value: "2"
                    - name: PROCESS_ID
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
                    - name: COORDINATOR_ADDRESS
                      value: "jax-cpu-job-workers-0-0.jax-cpu-job.default.svc.cluster.local:1234"
                  resources:
                    requests:
                      cpu: "1500m"
                      memory: "2Gi"
                    limits:
                      cpu: "2"
                      memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: jax-cpu-job
  namespace: default
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    jobset.x-k8s.io/jobset-name: jax-cpu-job
  ports:
    - port: 1234
      targetPort: 1234
      name: coordinator
